### ISSUE TITLE
Inspecting and updating Specifications

### ISSUE THREAD

**Issue by tmburnell** [tkaczmarzyk/specification-arg-resolver#101]
Is there any part of this library that will aid in inspecting or updating Specifications? 

1.  For testing reasons I would like to be able to inspect a specifications and see if a spec exists inside the where statement. 
2.  For Permissions I would like to inspect the in-coming request for a specific spec and under certain conditions perform a CRUD operation on it. 

I did not see anything in the documentation, but is there something else that would aid in this?

**Comment by tkaczmarzyk** [comment]
Might be partially related to #80

**Comment by tkaczmarzyk** [comment]
Closing as SpecificationBuilder was delivered recently. Please feel free to open another issue if it does not fill all your needs.
