### ISSUE TITLE
JoinFetch does not fill aliases in query context

### ISSUE THREAD

**Issue by tkleszczynski** [tkaczmarzyk/specification-arg-resolver#103]
Hi,
defining join fetch with aliases now requires to add @Join additonally in order to process them as a 'Fake' and provide required aliases for regular @Spec(s).
Shouldn't @JoinFetch be fake as well, therefore it would allow to define fetches with possibility to define aliases?

**Comment by tkaczmarzyk** [comment]
Hi @tkleszczynski  . Sorry for the huge delay. For whatever it's worth: v2.8.0 was just released and thanks to @jradlica great contribution, the issue should be resolved now.
