### ISSUE TITLE
JPA API 2.1 using hibernate artifact

### ISSUE THREAD

**Issue by tkleszczynski** [tkaczmarzyk/specification-arg-resolver#105]
Is it possible to remove hibernate JPA API artifact https://github.com/tkaczmarzyk/specification-arg-resolver/blob/52fe8d284f687ec86fea91b48f47d61dc6b32510/pom.xml#L214 and use the one defined by spring boot dependencies? That means:
```
<dependency>
    <groupId>javax.persistence</groupId>
    <artifactId>javax.persistence-api</artifactId>
    <version>${javax-persistence.version}</version>
</dependency>
```

**Comment by tkaczmarzyk** [comment]
Seems like a right thing to do

**Comment by tkaczmarzyk** [comment]
fixed with https://github.com/tkaczmarzyk/specification-arg-resolver/pull/144
