### ISSUE TITLE
annotation Join is not a repeatable annotation type

### ISSUE THREAD

**Issue by weber77** [tkaczmarzyk/specification-arg-resolver#106]
I am currently using this dependency for search and wanted to join more than one object to my search. I recieved and error saying _" java: net.kaczmarzyk.spring.data.jpa.web.annotation.Join is not a repeatable annotation type"_
![Screenshot from 2020-10-29 01-11-54](https://user-images.githubusercontent.com/44323398/97509944-e77bea00-1983-11eb-8c19-58414499ba44.png)

**Comment by jradlica** [comment]
Hi @weber77, repeatable joins are available from version: `2.5.0`, the screen shows that you are using `2.1.1`.

**Comment by weber77** [comment]
Oh okay thank you. I'll update that ASAP

**Comment by weber77** [comment]
Hi I updated it and it works great.
From the official maven website
<https://mvnrepository.com/artifact/net.kaczmarzyk/specification-arg-resolver/2.0.0>
it still proposes 2.0.0.
Maybe your team can update that.

Thank you,
Weber Dubois

**Comment by IncPlusPlus** [comment]
Hi, @weber77. I think you can close this issue now.
![image](https://user-images.githubusercontent.com/6992149/108520395-a2fcbd00-7298-11eb-96b2-87ab435401ff.png)

**Comment by weber77** [comment]
Oh sure
