### ISSUE TITLE
How to easily Unit Test the Specs

### ISSUE THREAD

**Issue by randyhbh** [tkaczmarzyk/specification-arg-resolver#111]
Hi, my issue here is that at the moment of the Unit Test my code is hard to build the Specification that is passed to the service class that then is passed to the repository one.

There are some tips you can give me or maybe some good approach to make the Unit Test as easiest as possible 🙏

**Comment by tkaczmarzyk** [comment]
realted to #80

**Comment by tkaczmarzyk** [comment]
delivered in https://github.com/tkaczmarzyk/specification-arg-resolver/pull/141, will be released today
