### ISSUE TITLE
Accept multiple @Spec for the same @Join alias

### ISSUE THREAD

**Issue by thesivis** [tkaczmarzyk/specification-arg-resolver#112]
When we have this code, a query with two joins was build

@Join(path = "sub", alias = "sub")
...

@And({
    @Spec(path = "sub.attribute1", params = "att1", spec = Equal.class),
    @Spec(path = "sub.attribute2", params = "att2", spec = Equal.class),})

The generated SQL was like

inner join sub sub0 .....
inner join sub sub1 .....
where 
sub0.attribute1 = ?
and sub1.attribute2 = ?

**Comment by mariseltm** [comment]
Please @thesivis review this pull request. Your solution is not integrated to master yet.

**Comment by thesivis** [comment]
@mariseltm I integrated my solution with master now. Can you verify please?

**Comment by wicaksono** [comment]
@tkaczmarzyk please merge this

**Comment by mariseltm** [comment]
@thesivis @wicaksono @tkaczmarzyk Are these changes already integrated with master? 
What version number do I have to set in my pom to use the updated library?

**Comment by tkaczmarzyk** [comment]
@wicaksono @mariseltm  Merged to master and will be released with 2.9.0 today.

**Comment by tkaczmarzyk** [comment]
v2.9.0 has been released and is now available in Maven Central
