### ISSUE TITLE
Can't perform nested @Or in @And

### ISSUE THREAD

**Issue by weber77** [tkaczmarzyk/specification-arg-resolver#115]
Hi sorry, this is not an issue related to you code. Rather I need help performing a query.
For example you've :

`Class Person{
  String firstname;
  String lastname;
  int height;
  int age
}
`
I want to query every person with height=1.5, age =25 and (firstname or lastname) = izel
I tried something like:

```
@RequestMapping("/Person")
public Object searchName(
        @And({
            @Spec(path="height", params="h", spec=Like.class),
            @Spec(path="age",  params="a", spec=Like.class)
             @Or(@Spec(path="firstname", params="name", spec=Like.class),
                      @Spec(path="lastname", params="name", spec=Like.class)
                )
        }) Specification<Person> personSpec) {

    return customerRepo.findAll(personSpec);
}
```

This doesn't work for me. Can anyone please give me the right syntax to do this?

**Comment by weber77** [comment]
I tried using the regular @Conjunction and have an error as in the image below


![Screen Shot 2021-03-16 at 6 01 18 PM](https://user-images.githubusercontent.com/44323398/111350308-42d41d80-8682-11eb-97b8-28b225365e6c.png)

![Screen Shot 2021-03-16 at 5 58 10 PM](https://user-images.githubusercontent.com/44323398/111349444-6a76b600-8681-11eb-8cd0-0d2dc438264b.png)

**Comment by jradlica** [comment]
Hi @weber77, following specification should work as expected:
```
@RequestMapping("/Person")
public Object searchName(
        @Conjunction(value = @Or({
				@Spec(path = "firstName", params = "name", spec = Like.class),
				@Spec(path = "lastName", params = "name", spec = Like.class)
		}), and = {
				@Spec(path = "height", params = "height", spec = Equal.class),
				@Spec(path = "age", params = "age", spec = Equal.class),
		})  Specification<Person> personSpec) {

    return customerRepo.findAll(personSpec);
}
```

**Comment by weber77** [comment]
Okay thanks a million let me test it out right away!😀

**Comment by weber77** [comment]
works perfectly men. thanks again
