### ISSUE TITLE
how to pass parameters as POST body?

### ISSUE THREAD

**Issue by fuesec** [tkaczmarzyk/specification-arg-resolver#118]
How is the JSON body supposed to look like when you try to pass the spec parameters as a POST body instead of GET parameters? I only got the following example to work if I use GET. The following JSON body did not work for the following request:

```
{
 "someId": "myid-1234"
}
```

```
    @PostMapping(path = "/filter")
    public List<ObjectTO> filterObjects(@Spec(path="someId", spec= In.class) Specification<ObjectBE> specification) {
        return service.filter(specification));
    }
```

**Comment by tkaczmarzyk** [comment]
basic json support will be included in v2.13.0 (released today)
