### ISSUE TITLE
Use one @Join alias for multiple @Spec

### ISSUE THREAD

**Issue by MikLay** [tkaczmarzyk/specification-arg-resolver#119]
I have a problem with: 

![image](https://user-images.githubusercontent.com/30328497/115049057-f5e2a180-9ee2-11eb-8c93-5f076b83bd88.png)
It creates query with two joins for getting date

```
inner join timetables t0 .....
inner join timetables t1 ....
......
where
t0.startTime = ?
and t1.endTime = ?
```

But I need to get query like 
```
inner join timetables t0 ....
......
where
t0.startTime = ?
and t0.endTime = ?
```

**Comment by Meephistoo** [comment]
in fact this error occurs for every where condition of joined entity  - so we have not @And but @Or

**Comment by YomnaFekry** [comment]
I have the same problem

**Comment by rishisha19** [comment]
Do we have any solution for this issue?

**Comment by mariseltm** [comment]
I have the same problem. Any solution or alternative for this please?

**Comment by tkaczmarzyk** [comment]
@rishisha19 @YomnaFekry @Meephistoo @MikLay v2.9.0 has been released today and it contains a fix for this. Thank you for patience.
