### ISSUE TITLE
Work with contains string filter

### ISSUE THREAD

**Issue by nesrinesghaier** [tkaczmarzyk/specification-arg-resolver#124]
I wanted to check if it is possible to filter using a specific string when any of the class fields content contains it?

**Comment by klesniak1** [comment]
Hi,

As I understood question correctly - your goal is to check if filter matches with any of the class fields.

It's possible to achieve described behaviour/filter in following way: 
 1) for each class field there should be defined a separate spec
 2) each of defined spec should use the same param name
 3) all specs should be combined with `@Or`

Code example:
`public class ContainsE2eTest extends E2eTestBase {

	@Controller
	public static class TestController {

		@Autowired
		CustomerRepository customerRepo;

		@RequestMapping(value = "/contains/customers", params = {"stringValue"})
		@ResponseBody
		public Object findByStringValue(@Or({ // for each class field there should be defined a separate spec
				@Spec(path = "firstName", params = "stringValue", spec = LikeIgnoreCase.class), // Like and LikeIgnoreCase class is responsible for searching result containing passed parameter in given path
				@Spec(path = "lastName", params = "stringValue", spec = LikeIgnoreCase.class) }) Specification<Customer> spec) {
			return customerRepo.findAll(spec);
		}
	}

	@Test
	public void findByStringValue() throws Exception {
		customer("TestFirstName", "TestLastName") // creating new Customer and saving to DB
				.build(em);

		mockMvc.perform(get("/contains/customers")
				.param("stringValue", "TestLastName")
				.accept(MediaType.APPLICATION_JSON))
				.andExpect(status().isOk())
				.andExpect(jsonPath("$").isArray())
				.andExpect(jsonPath("$[?(@.lastName=='TestLastName')]").exists())
				.andExpect(jsonPath("$[1]").doesNotExist());
	}
}`

**Comment by tkaczmarzyk** [comment]
I'm assuming that the snippet above answers the question. Feel free to reopen the topic if you need more help.
