### ISSUE TITLE
Can you add SPeL in @Spec constVal with value  from headers?

### ISSUE THREAD

**Issue by sanjeevghimire** [tkaczmarzyk/specification-arg-resolver#132]
I tried all possible scenarios:

```
           @Spec(path = "me.entityCode", constVal = "#{request.getHeader(\"" + EPConstants.MEDICAL_ENTITY_CODE_HEADER + "\")}", valueInSpEL = true, spec = Equal.class)           
 @Spec(path = "me.entityCode", constVal = "#{headers['" + EPConstants.MEDICAL_ENTITY_CODE_HEADER + "']}", valueInSpEL = true, spec = Equal.class)

```
both gives invalid SpEL. Any idea why its giving invalid SpEL expression?

**Comment by tkaczmarzyk** [comment]
specification-arg-resolver uses Spring's `EmbeddedValueResolver`. It basically wrapps provided AbstractApplicationContext:
```
 new EmbeddedValueResolver(applicationContext.getBeanFactory())
```
After quick look, I don't see an option to resolve your expression via this component (but maybe I'm missing something).

What did work for me is the following:
1. Define a RequestScoped bean which has access to the current HttpServletRequest (and therefore can access any http header):
```
public class HeaderHolder {

	@Autowired
	  private HttpServletRequest httpServletRequest;
	
	public Object getHeader() {
		return httpServletRequest.getHeader("myHeaderName");
	}
}

```
2. use "@" notation to access this bean in you SpEL: `#{@headerHolder.header}`

Please note that it was just a quick try and I did not evaluated this approach thoroughly -- just checked and expression was properly evaluated.

**Comment by tkaczmarzyk** [comment]
Actually, also please observe this PR: https://github.com/tkaczmarzyk/specification-arg-resolver/pull/133 which contains direct header support
