### ISSUE TITLE
Filter on join table attribute

### ISSUE THREAD

**Issue by ekalabs** [tkaczmarzyk/specification-arg-resolver#14]
Firstly, thanks for your open source contribution. 

I would like to know if what I am trying is supported by the specification-arg-resolver. For example, I would like to retrieve all customers whose city of address matches 'Montreal' in the below entity model.

```
@Entity
public class Customer implements Serializable {
    @Id @GeneratedValue
     private Long id;
    @OneToMany
    @JoinColumn(name = "customerId")
    private List<Address> addresses;
}

@Entity
public class Address implements Serializable {
    @Id
    private Long contactId;
    private String city;
}
```

I tried below spec annotation, but it didn't work.

```
@RequestMapping(value = "", params = { "city" })
@ResponseBody
public Iterable<Customer> filterCustomersByCity(
        @JoinFetch(paths = {"addresses" })
        @Spec(path="addresses.city", params="city", spec=In.class)
        final Specification<Customer> customersByCitySpec) {
         return customerRepo.findAll(customersByCitySpec);
```

   }

I get below error

java.lang.IllegalStateException: Illegal attempt to dereference path source [null.addresses] of basic type
    at org.hibernate.jpa.criteria.path.AbstractPathImpl.illegalDereference(AbstractPathImpl.java:98)
    at org.hibernate.jpa.criteria.path.AbstractPathImpl.get(AbstractPathImpl.java:182)
    at net.kaczmarzyk.spring.data.jpa.domain.PathSpecification.path(PathSpecification.java:42)
    at net.kaczmarzyk.spring.data.jpa.domain.In.toPredicate(In.java:64)
    at org.springframework.data.jpa.domain.Specifications$1.toPredicate(Specifications.java:64)
    at org.springframework.data.jpa.domain.Specifications.toPredicate(Specifications.java:114)
    at net.kaczmarzyk.spring.data.jpa.domain.Conjunction.toPredicate(Conjunction.java:58)

On debugging, I see it is not able to fetch city field. What am I doing wrong? Could you please point me in right direction.

**Comment by tkaczmarzyk** [comment]
Thank you, this one might be interesting.

Essentially, it can't work as you described, because it wouldn't be a valid JPA query -- a join is needed.

I think there are the following options here:

1. A subquery:
 `select c from Customer c where exist (select a from addresses a where a.customer = c and a.city in :cities)`

2. Join + distinct: `select distinct c from Customer c inner join c.addresses a where a.city in :cities`


None of them is currently supported. But I'll think about it, it would be definitely a useful feature (and fun to implement too)!

For now you can only implement your own `PathSpecification` which would have to do the join itself. But it might be not worth the required effort, unless you want to combine it with other specs.

I'll asses the options and come back to you! Thanks for reporting.

**Comment by ekalabs** [comment]
I was in assumption that ' @JoinFetch(paths = {"addresses" }) ' along with ' @Spec(path="addresses.city" ' reference to OneToMany attribute 'addresses' + join-table attribute 'city' will produce the specification object with join + distinct you mentioned in option 2.

I would be happy to work with you on this. Let me know how I can help. Thanks for your prompt reply and effort.

**Comment by tkaczmarzyk** [comment]
`@JoinFetch` adds JPA fetch join (which just initializes collections, but is not used for filtering).
What is needed, is a regular join.

I started thinking about possible syntax...

**Option 1**: add a join implicitly, i.e. allow paths like `addresses.city` in regular `@Spec` -- I don't like this one, it feels like too much magic

**Option 2**: Additional annotation for join
```
@Join(on="addresses", alias="address"
@Spec(path="address.city", spec=In.class)
```

**Option 3**: nested spec:
```
@Spec(path="firstName", spec=Like.class, join=@JoinedSpec(on="addresses", path="city", spec=In.class)
```

In the case above, the filtering would be on both simple attribute (`firstname`) and on a joined one (`address.city`). In case when only the latter is required, I would allow using just `@JoinedSpec`, without `@Spec` wrapper.


I like Option 2, but it wouuld be cumbersome when `@Or` or `@And` was to be used. I think Option 3 is the way to go. 

Separate issue is ensuring `distinct` to be used in the query. I'm afraid it might be impossible with Spring Data Specification API...

**Comment by tkaczmarzyk** [comment]
Update, `distinct` is not a problem :)

**Comment by ekalabs** [comment]
Nice to hear from you on the options and explanation. I see why option 1 & 2 might not be best choice. But with option 3,

@Spec(path="firstName", spec=Like.class, join=@JoinedSpec(on="addresses", path="city", spec=In.class)

I did not understand why JoinedSpec of city is tied to Spec  of firstName. Couldn't we do below?

@And({
@Spec(path="firstName", spec=Like.class, params="name")
@JoinedSpec(on="addresses", path="city", spec=In.class, params="city")
})

**Comment by jbaezml** [comment]
HI!. I have the same problem. This problem is solved ?, How?

Regards

**Comment by ashrafsarhan** [comment]
The same issue here, Are still working on it?

**Comment by pedrophalves** [comment]
I am with the same issue and since @Join and join parameter from @Spec is not working anymore I can't even try the options you gave previously. What else can I try?

Additionaly I want to thank you the your API. =)

**Comment by tkaczmarzyk** [comment]
Hi Guys, sorry for the delay. Join support has been added (see README and CHANGELOG). I will double test it and release version 1.0.0 of the lib this week.

**Comment by tkaczmarzyk** [comment]
v1.0.0 with join support has been released.
