### ISSUE TITLE
Path variables from `@RequestMapping` annotation above the class are not included in springdoc api documentation

### ISSUE THREAD

**Issue by khajduga** [tkaczmarzyk/specification-arg-resolver#183]
For following controller class:
```
@RestController
@RequestMapping("/sample/{shopName}/")
public class SampleController {

	@GetMapping("/customers")
	public List<Customer> getShopCustomers(@Spec(path = "shopName", pathVars = "shopName", spec = Like.class) Specification<Customer> specification) {
		return repo.findAll(specification);
	}

}
```

Automated API documentation is generated without path variable parameter (it shows `No parameters`):
![no-parameters](https://user-images.githubusercontent.com/89588406/210213027-a13fe5e7-c9cc-40be-97a9-815eb1d4e719.png)

It should contain information about `shopName` path variable.

**Comment by tkaczmarzyk** [comment]
(after investigation, we realized that it was due to misconfiguration = not a bug)
