### ISSUE TITLE
How to add NotEqual domain in Spec 

### ISSUE THREAD

**Issue by bhumikat** [tkaczmarzyk/specification-arg-resolver#19]
Firstly, thanks for your open source contribution.

I see there is no NotEqual implemented. If I want to do such NotEqual, is it possible with exist impl? 
May I know specific reason that is not provided yet?

Let's say example:
and = @Spec(path = "data",spec = **NotEqual**.class,constVal= 'inactive'))

**Comment by tkaczmarzyk** [comment]
available in v1.1.1
