### ISSUE TITLE
Pageable and Sort handling

### ISSUE THREAD

**Issue by marceloverdijk** [tkaczmarzyk/specification-arg-resolver#22]
Hi,

I don't know if this is the appropriate channel for asking a question. Anyway here I go :-)

I really like `@Spec(path="firstName", params="name", spec=Like.class)`
so we define the the `name` param to be used by the API client and internally use the actual `firstName` path.

Using the specification together with a `Pageable` or even a plain `Sort` I would like to employ the same. So `sort=name` becomes sorting on `firstName`.
I understand this goes beyond this lib but I can imagine you bumped against this as well. What would be your recommendation?

**Comment by tkaczmarzyk** [comment]
Hi, thank you for the feedback. Spring Data provides a way to handle it. You can use `Pageable` and `Sort` as Controller parameters. Then Spring Repository has suitable method to pass both `Specification` and `Pageable`/`Sort` into.

**Comment by marceloverdijk** [comment]
Yes I understand. I only wondered how you personally handle the actual names of the field in your exposed API vs the internal names.

Your lib can handle that nicely using the `params` vs `path` attributes.
So I wondered if you had to do this for pageable as one and how you solved it. Of course I can create my own implementation / argument resolves around Spring's Pageable to keep a mapping between API names and internal technical column names.

**Comment by tkaczmarzyk** [comment]
ah, ok, now I understand. It's a simple implementation in the lib, it first takes `path` value, if it it's absent then it defaults to `params`. I didn't do that for `Pageable` nor `Sort`. I don't know any other way than just implementing a custom `HandlerMethodArgumentResolver`.

**Comment by marceloverdijk** [comment]
Yes that what I was doing. Creating my `HandlerMethodArgumentResolver` integrating `Pageable` and a custom filter solution using `Querydsl` and then I bumped against your lib.
