### ISSUE TITLE
Json body params should not impose restrictions on requests 

### ISSUE THREAD

**Issue by vanjad-sixt** [tkaczmarzyk/specification-arg-resolver#249]
Including a jsonPath parameter in the spec throws an exception when either:
- Content-type header is not defined
- Content-type is not application/json
- content is empty

This results in errors when used in GET requests, which most commonly do not have a request body or a Content-type header.
When using a mix of path, query and json-body parameters (all of which should be optional) on different endpoints (GET, POST), it forces the GET requests to provide a Content-type header and an empty json object body, which is not semantically correct.

It also enforces an inconsistent behavior - the client is allowed to omit a parameter in the JSON body, but is not allowed to omit the entire body. On the opposite, omitting query parameters entirely is allowed.

I would argue that json body parameters should be fully optional and do not enforce requirements on content-type or even JSON body shape.

I can provide a PR, but I would like to hear what you think? cc: @tkaczmarzyk @jradlica @vahundos

**Comment by vanjad-sixt** [comment]
A little bit more background:

With the old version of spec-resolver:
We have a specification with many parameters (cca. 50). It is being used in 3 GET and 3 POST endpoints.
One of the parameters is the entity ID.
3 POST endpoints are receiving a huge list of IDs, making the URL too long.
So we (manually) added the IDs to a custom JSON body and created a specification wrapper class, to marry the list of IDs to the existing (auto-resolved) spec object in the controller.
The 3 GET endpoints do not use the ID list extension (and as such, don't have body/content-type).

So when we eliminated the wrapper and migrated the ID list to jsonPath, which works great for the POST endpoints, but throws "Invalid mime type "null": 'mimeType' must not be empty" exception in the GET endpoints.

**Comment by jradlica** [comment]
Hey @vanjad-sixt ,

thanks for the detailed description. I agree that JSON body parameters should be optional. They already are, but an empty JSON body is still required - it seems that it doesn't make sense and should be improved/fixed.

I have approved your PRs (thank you for your contribution :medal_sports:). I assume that the changes will be released in the upcoming week. (Could you find a moment for this @tkaczmarzyk?)

Additional comment:
Currently, SAR does not support setting the jsonParam parameter as required. We already have a task/issue for this - #243  (I'll try to take a look at this in the upcoming week)

**Comment by tkaczmarzyk** [comment]
Thank you very much, @vanjad-sixt . Both PRs have been merged and v2.19.0 and v3.1.0 released :)
