### ISSUE TITLE
duplicate buildSpecification call in OrSpecificationResolver

### ISSUE THREAD

**Issue by shihyuho** [tkaczmarzyk/specification-arg-resolver#28]
[OrSpecificationResolver line 58](https://github.com/tkaczmarzyk/specification-arg-resolver/blob/master/src/main/java/net/kaczmarzyk/spring/data/jpa/web/OrSpecificationResolver.java#L58)

I think it can be replaced with `innerSpecs.add(innerSpec);`

**Comment by tkaczmarzyk** [comment]
Thank you very much for reporting. This has been fixed and will be released in v2.0.0
