### ISSUE TITLE
Extract URL path values

### ISSUE THREAD

**Issue by matthewsommer** [tkaczmarzyk/specification-arg-resolver#30]
Is there any way to extract URL paths to use in a spec?

I have /rest/customers/{id}/order?state=pending but I don't understand how I can extract the {id} from the URL path to use in a spec.

It works if I do /rest/orders?id=1&state=pending but I can't use that paradigm because our API already has the ID in the URL path.

Of course it's easy to get the value using Spring but I'm not sure how to get the value into the spec...
`@PathVariable("id") String id`

**Comment by tkaczmarzyk** [comment]
Hi, this is not supported at this time. I can try to add it, but it may take a while.. Feel free to submit a PR.

**Comment by matthewsommer** [comment]
Okay. Thanks for getting back so quickly. I probably won't be able to get to it for awhile. I started adding support for LocalDateTime but haven't had time to finish it: https://github.com/tkaczmarzyk/specification-arg-resolver/compare/master...matthewsommer:master
