### ISSUE TITLE
Pass multiple params for In Spec as comma separated

### ISSUE THREAD

**Issue by makihor** [tkaczmarzyk/specification-arg-resolver#32]
hi! frstly, - nice lib! 
question: is it possible to pass multiple params as csv? for example:
?myFilter=val1,val2,val3 instead of ?myFilter=val1&myFilter=val2&myFilter=val3

Thanks.

**Comment by tkaczmarzyk** [comment]
Hi, it is not supported. But since it seems that users need this feature, I'll try to add it soon :)

**Comment by rcbandit111** [comment]
Hi, is this feature implemented? I need it into my project.

**Comment by tkaczmarzyk** [comment]
released in v2.2.0
