### ISSUE TITLE
Join only if spec is used

### ISSUE THREAD

**Issue by ecattez** [tkaczmarzyk/specification-arg-resolver#33]
public Page<Application> getAll(@And({
                                            @Spec(path = "disabled", params = "status", spec = WithStatus.class),
                                            @Spec(path = "name", params = "name", spec = StartsWith.class),
                                            @Spec(path = "corridors", config = "inventory", params = "inventories[]", spec = IdIn.class)
}) Specification specification, Pageable pageable)

In my example, "corridors" is a Many-To-Many association between Application and Corridor but we can call the web service by filtering on inventories (list of ids). Each corridor has an inventory reference.

So, I did a config = "inventory", because I need to join Application and Corridor IF AND ONLY IF inventories are found. That's why I can't use @Join(s) in this case.

Is there a more elegant way to do ?

Could it be possible to improve the @Spec to pass @Join(s) ?

**Comment by tkaczmarzyk** [comment]
I'm not sure if I understand the scenario. What is an "inventory" in this case? An entity? How is it related to Application and Corridor?

**Comment by tkaczmarzyk** [comment]
(closing as improvements in v2.0.0 should solve it)
