### ISSUE TITLE
WebMvcConfigurerAdapter is deprecated, what alternatives?

### ISSUE THREAD

**Issue by ortonomy** [tkaczmarzyk/specification-arg-resolver#39]
I'm not really that confident using Java, but in the latest version of Spring, ``WebMvcConfigurerAdapter`` is deprecated. Where should I wire in the Specficiation Argument Resolver now?

**Comment by tkaczmarzyk** [comment]
@ortonomy `WebMvcConfigurerAdapter` is deprecated because the interface which it implements has now default methods (thanks to Java8). You can implement `WebMvcConfigurer` and wire `SpecificationArgumentResolver` exactly the same way.
