### ISSUE TITLE
Add ability to control position of % on Like

### ISSUE THREAD

**Issue by mrc535s** [tkaczmarzyk/specification-arg-resolver#40]
Like is limited to %Homer%.  Can we add the ability to add % at end or beginning only, so %Homer or Homer%.  Maybe a new class for each called LikeBeginning & LikeEnd?

**Comment by tkaczmarzyk** [comment]
Hi @mrc535s, thanks for the suggestion. This is in progress (most likely will use separate spec classes, such as `StartsWith`, `EndsWith`). Will be released in 2.1.0 (by the end of Febuary). Before that happens, you can easily create them for your project -- just take a look on the `Like.java`, copy and modify :)

**Comment by tkaczmarzyk** [comment]
(included in v2.1.0)
