### ISSUE TITLE
Create a CommonFilter

### ISSUE THREAD

**Issue by sorrentinov** [tkaczmarzyk/specification-arg-resolver#45]
Hi,

Based on your examples I would to implement a Common Filter in this way:

`@Join(path= "orders", alias = "o")) // alias specified for joined path`
`@Spec(path="o.id", params="orderId", spec=Equal.class)`
`public interface CommonFilter<T> extends Specification<T> {   
}`

`public interface CustomerFilter extends CommonFilter<Customer> {
}
`

In this way every times I need to filter associated order on an entity I could extends CommonFilter. Is there a way to do this? I try but receive an error that "o" is not an attribute of  Customer

Best Regards
Vincenzo

**Comment by tkaczmarzyk** [comment]
Hi, thank you for reporting, this must be a bug. I will take a look on it.

**Comment by tkaczmarzyk** [comment]
Fixed in v2.2.2
