### ISSUE TITLE
java.time.Instant conversion failed

### ISSUE THREAD

**Issue by vladimirsvicevicsrb** [tkaczmarzyk/specification-arg-resolver#50]
Hi All,

I'm trying to retieve instant as request parameter and parse it using Specification library.
However, I'm facing the following issue. I tried everything I found on internet, but without success.

Controller: 
`	@GetMapping("/calendar-item-users/search")
	public ResponseEntity<List<CalendarItemUserDTO>> findCalendarItemUsers(@And({
			@Spec(path = "user.id", params = "userId", spec = In.class),
			@Spec(path = "calendarItem.id", params = "calendarItemId", spec = In.class),
			@Spec(path = "startTime", params = "startTime", spec = GreaterThanOrEqual.class),
			@Spec(path = "endTime", params = "endTime", spec = LessThanOrEqual.class)}) Specification<CalendarItemUser> spec) {
		List<CalendarItemUserDTO> fetchedCalendarItemUsers = calendarItemUserService.findAllBySpecification(spec);
		return ResponseEntity.ok().body(fetchedCalendarItemUsers);
	}`
Entity:
`public class CalendarItemUser implements Serializable {

    private static final long serialVersionUID = 1L;

    @Column(name = "start_time")
    private Instant startTime;

    @Column(name = "end_time")
    private Instant endTime;
`

Error:
`{
    "type": "https://www.jhipster.tech/problem/problem-with-message",
    "title": "Internal Server Error",
    "status": 500,
    "detail": "Parameter value [2019-05-04T22:11:29Z] did not match expected type [java.time.Instant (n/a)]; nested exception is java.lang.IllegalArgumentException: Parameter value [2019-05-04T22:11:29Z] did not match expected type [java.time.Instant (n/a)]",
    "path": "/api/calendar-item-users/search",
    "message": "error.http.500"
}`

Could you please have a look?
Thanks,
Vladimir

**Comment by Neloop** [comment]
Up... support for `Instant` would be deal-breaker for us, so we could start using this awesome library

**Comment by CristianZatt** [comment]
Hi, the project I'm working needed OffsetDateTime support, so I added it, created a [merge request](https://github.com/tkaczmarzyk/specification-arg-resolver/pull/58) and build my own snapshot while it's not merged.

If it's of your interest, you can to take a look at my [MR](https://github.com/tkaczmarzyk/specification-arg-resolver/pull/58) and implement Instant support like I did for OffsetDateTime, so you can use it too while not officially supported.

**Comment by tkaczmarzyk** [comment]
@vladimirsvicevicsrb @Neloop @CristianZatt  Thank you for your contributions. Based on this issue as well as some other issues and pull requests the Instant support, as well as other conversions and more comprehensive conversion support, were added to version 2.4.0 (just released)
