### ISSUE TITLE
Pageable with Count Query Fails Test

### ISSUE THREAD

**Issue by jlaureano** [tkaczmarzyk/specification-arg-resolver#53]
https://github.com/tkaczmarzyk/specification-arg-resolver/blob/4af6682079b26e7f0467b4a5d1a6982e936c2d70/src/test/java/net/kaczmarzyk/AvoidingRedundantJoinE2eTest.java#L74

Steps to reproduce:
Add 30 more em.persist() calls, then add pagination so it forces a count query

```mockMvc.perform(get("/movies?star=Homer&director=Anderson&page=0&size=3"))```

```mockMvc.perform(get("/movies?star=Homer&page=0&size=2"))```

```mockMvc.perform(get("/movies?page=0&size=3"))```

**Comment by rcbandit111** [comment]
Hi @jlaureano I would like to test just for curiosity this because I have similar code. Can you share the entire JUnit file?

**Comment by jlaureano** [comment]
@rcbandit111  In AvoidingRedundantJoinE2eTest.java modify as follow

`@Before
	public void persistTestData() {
		em.persist(new Movie("Bart's Not Dead",
				asList(new Person("Bart Simpson"), new Person("Homer Simpson")),
				asList(new Person("Bob Anderson"))));
		
		em.persist(new Movie("Heartbreak Hotel",
				asList(new Person("Marge Simpson"), new Person("Lisa Simpson")),
				asList(new Person("Steven Dean Moore"))));
		
		em.persist(new Movie("My Way or the Highway to Heaven",
				asList(new Person("Marge Simpson"), new Person("Homer Simpson")),
				asList(new Person("Rob Oliver"))));
		
		em.persist(new Movie("Bart's Not Dead",
				asList(new Person("Bart Simpson"), new Person("Homer Simpson")),
				asList(new Person("Bob Anderson"))));
		
		em.persist(new Movie("Heartbreak Hotel",
				asList(new Person("Marge Simpson"), new Person("Lisa Simpson")),
				asList(new Person("Steven Dean Moore"))));
		
		em.persist(new Movie("My Way or the Highway to Heaven",
				asList(new Person("Marge Simpson"), new Person("Homer Simpson")),
				asList(new Person("Rob Oliver"))));
		
		em.persist(new Movie("Bart's Not Dead",
				asList(new Person("Bart Simpson"), new Person("Homer Simpson")),
				asList(new Person("Bob Anderson"))));
		
		em.persist(new Movie("Heartbreak Hotel",
				asList(new Person("Marge Simpson"), new Person("Lisa Simpson")),
				asList(new Person("Steven Dean Moore"))));
		
		em.persist(new Movie("My Way or the Highway to Heaven",
				asList(new Person("Marge Simpson"), new Person("Homer Simpson")),
				asList(new Person("Rob Oliver"))));
		
		em.persist(new Movie("Bart's Not Dead",
				asList(new Person("Bart Simpson"), new Person("Homer Simpson")),
				asList(new Person("Bob Anderson"))));
		
		em.persist(new Movie("Heartbreak Hotel",
				asList(new Person("Marge Simpson"), new Person("Lisa Simpson")),
				asList(new Person("Steven Dean Moore"))));
		
		em.persist(new Movie("My Way or the Highway to Heaven",
				asList(new Person("Marge Simpson"), new Person("Homer Simpson")),
				asList(new Person("Rob Oliver"))));
		
		em.persist(new Movie("Bart's Not Dead",
				asList(new Person("Bart Simpson"), new Person("Homer Simpson")),
				asList(new Person("Bob Anderson"))));
		
		em.persist(new Movie("Heartbreak Hotel",
				asList(new Person("Marge Simpson"), new Person("Lisa Simpson")),
				asList(new Person("Steven Dean Moore"))));
		
		em.persist(new Movie("My Way or the Highway to Heaven",
				asList(new Person("Marge Simpson"), new Person("Homer Simpson")),
				asList(new Person("Rob Oliver"))));
		
		em.persist(new Movie("Bart's Not Dead",
				asList(new Person("Bart Simpson"), new Person("Homer Simpson")),
				asList(new Person("Bob Anderson"))));
		
		em.persist(new Movie("Heartbreak Hotel",
				asList(new Person("Marge Simpson"), new Person("Lisa Simpson")),
				asList(new Person("Steven Dean Moore"))));
		
		em.persist(new Movie("My Way or the Highway to Heaven",
				asList(new Person("Marge Simpson"), new Person("Homer Simpson")),
				asList(new Person("Rob Oliver"))));
		
		em.persist(new Movie("Bart's Not Dead",
				asList(new Person("Bart Simpson"), new Person("Homer Simpson")),
				asList(new Person("Bob Anderson"))));
		
		em.persist(new Movie("Heartbreak Hotel",
				asList(new Person("Marge Simpson"), new Person("Lisa Simpson")),
				asList(new Person("Steven Dean Moore"))));
		
		em.persist(new Movie("My Way or the Highway to Heaven",
				asList(new Person("Marge Simpson"), new Person("Homer Simpson")),
				asList(new Person("Rob Oliver"))));
		
		em.persist(new Movie("Bart's Not Dead",
				asList(new Person("Bart Simpson"), new Person("Homer Simpson")),
				asList(new Person("Bob Anderson"))));
		
		em.persist(new Movie("Heartbreak Hotel",
				asList(new Person("Marge Simpson"), new Person("Lisa Simpson")),
				asList(new Person("Steven Dean Moore"))));
		
		em.persist(new Movie("My Way or the Highway to Heaven",
				asList(new Person("Marge Simpson"), new Person("Homer Simpson")),
				asList(new Person("Rob Oliver"))));
		
		em.persist(new Movie("Bart's Not Dead",
				asList(new Person("Bart Simpson"), new Person("Homer Simpson")),
				asList(new Person("Bob Anderson"))));
		
		em.persist(new Movie("Heartbreak Hotel",
				asList(new Person("Marge Simpson"), new Person("Lisa Simpson")),
				asList(new Person("Steven Dean Moore"))));
		
		em.persist(new Movie("My Way or the Highway to Heaven",
				asList(new Person("Marge Simpson"), new Person("Homer Simpson")),
				asList(new Person("Rob Oliver"))));
		
		em.persist(new Movie("Bart's Not Dead",
				asList(new Person("Bart Simpson"), new Person("Homer Simpson")),
				asList(new Person("Bob Anderson"))));
		
		em.persist(new Movie("Heartbreak Hotel",
				asList(new Person("Marge Simpson"), new Person("Lisa Simpson")),
				asList(new Person("Steven Dean Moore"))));
		
		em.persist(new Movie("My Way or the Highway to Heaven",
				asList(new Person("Marge Simpson"), new Person("Homer Simpson")),
				asList(new Person("Rob Oliver"))));
	}`

`@Test
	public void performsEachJoinOnlyOnce() throws Exception {
		mockMvc.perform(get("/movies?star=Homer&director=Anderson&page=0&size=3"))
			.andExpect(status().isOk())
			.andExpect(jsonPath("$.totalElements").value(1));
		
		assertThat()
			.numberOfPerformedHqlQueriesIs(1)
			.andQueryWithIndex(0)
			.hasNumberOfJoinsForPath(".stars", 1)
			.hasNumberOfJoinsForPath(".directors", 1);
	}`

**Comment by tkaczmarzyk** [comment]
the fix is merged - this should be fixed in v2.2.1 release (planned for this week, stay tuned)

**Comment by tkaczmarzyk** [comment]
Thanks to the great contributors, version 2.2.1 has been just released and deployed to the Maven repo (it might take a few hours until it's visible there).
This should fix the reported issue so I'm closing it (but let me know if you are still experiencing it!)
Sorry for the delay!
