### ISSUE TITLE
date and time filter 

### ISSUE THREAD

**Issue by christiantanzmann** [tkaczmarzyk/specification-arg-resolver#54]
Hi, 
in a mssql db table I have a column with the name 'starttime' of type 'datetime'. And a value is stored like this "2018-06-29 15:04:55.203". In my json results I have a iso8601 string like this: "2018-07-06T09:05:57.093+0000".

Now I have defined a Spec like this: 

```
@Spec(path = "starttime", spec = Equal.class),
@Spec(path = "starttime", params = { "starttime_gt" }, spec = GreaterThan.class /*, config = "yyyy-MM-dd'T'HH:mm:ss"*/),
@Spec(path = "starttime", params = { "starttime_lt" }, spec = LessThan.class /*, config = "yyyy-MM-dd'T'HH:mm:ss"*/),
@Spec(path = "starttime", params = { "starttime_gte" }, spec = GreaterThanOrEqual.class),
@Spec(path = "starttime", params = { "starttime_lte" }, spec = LessThanOrEqual.class),
```

I know the default config is "yyyy-MM-dd" and that works mostly. Especially for exactly one day with a gte and a lte it dosnt work. Anyway how can a filter a special hour. For this case I got no results.  Maybe the config pattern is a problem or the comparison with the values stored in db.
Can you give me a hint or is it really an issue?
Thanks a lot.

**Comment by sisela** [comment]
So, I am trying it again and solve my problem. The default dataformat for the converter can be overwritten by an own config. So my dates have the format 2018-07-11T14:33:56.338Z and in that case the default date format ignores the time component. So I have to override the dateformat with 
`@Spec(path = "starttime", params = { "starttime_gt" }, spec = GreaterThan.class, config = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")`
and than it works like a charm.
So its important which format the delivered date has. 
[https://docs.oracle.com/cloud/latest/big-data-discovery-cloud/BDDDP/rdp_config_dates.htm#BDDDP-reference_C54EA1E5CEC74AF3832204EDE334DFFB ](https://docs.oracle.com/cloud/latest/big-data-discovery-cloud/BDDDP/rdp_config_dates.htm#BDDDP-reference_C54EA1E5CEC74AF3832204EDE334DFFB )

**Comment by tkaczmarzyk** [comment]
(the documentation should be enhanced to make it more clear for the future)

**Comment by tkaczmarzyk** [comment]
README has been updated.
