### ISSUE TITLE
Issue with annotated specification interfaces and caching

### ISSUE THREAD

**Issue by wjtlopez** [tkaczmarzyk/specification-arg-resolver#55]
Hi there,

I am using spring-boot-starter-cache:2.0.3.RELEASE without any additional configuration. I'm also using an annotated specification interface:

@And({
        @Spec(path = "name", spec = Like.class),
        @Spec(path = "indicatorClassification.id", params = "indicatorClassification", spec = Equal.class),
        @Spec(path = "toDate", params = "isActive", spec = Null.class)})
public interface IndicatorSearchSpecification extends Specification<Indicator> { 
    
}

And I have ` @Cacheable` on the repository

`
    @Cacheable("indicators")
    Page<Indicator> findAll(Specification specification, Pageable pageable);
`
I've found that every API request results in a new key being added to the cache as it is failing to compare keys accurately. I've digged through and this has something to do with the usage of CGLIB, but any further is beyond my understanding and I'm sure you will know far more about this than me :).

Let me know if I can help with any further info. Thanks for the great library!
Regards,
Warren

**Comment by tkaczmarzyk** [comment]
Hi @wjtlopez . Sorry for the huge delay. For whatever it's worth: v2.8.0 was just released and thanks to @jradlica great contribution, the library should work with cache as expected now.
