### ISSUE TITLE
EqualIgnoreCase for enum

### ISSUE THREAD

**Issue by CristianZatt** [tkaczmarzyk/specification-arg-resolver#56]
Suggestion for feature increment:
 
Consider "type" as a enum that can be WIDGET or PANEL, and genericSearch being a string with value "WIDGET"

When using:

@Spec(path = "type", params = "genericSearch", spec = EqualIgnoreCase.class)
or
@Spec(path = "type", params = "genericSearch", spec = Equal.class)

the result is as expected, but when genericSearch has value "widget", EqualIgnoreCase.class brings nothing, it behaves like Equal.class for enums.

So my suggestion is spec = EqualIgnoreCase.class take in consideration enum names.

**Comment by tkaczmarzyk** [comment]
added in v2.5.0 (just released)
