### ISSUE TITLE
Support OffsetDateTime

### ISSUE THREAD

**Issue by CristianZatt** [tkaczmarzyk/specification-arg-resolver#57]
Hi, awesome library!!! Just having some issues to adopt it.
Is there a way to use spec=Between.class for OffsetDateTime?

I have noticed only LocalDate and LocalDateTime converter, and when tring to use OffsetDateTime I get:
Parameter value [04-06-2019T17:42:53.444+02.00] did not match expected type [java.time.OffsetDateTime (n/a)]

**Comment by CristianZatt** [comment]
created a pull request https://github.com/tkaczmarzyk/specification-arg-resolver/pull/58

**Comment by youagree** [comment]
> created a pull request #58

hi, i need this bugfix, do you think this mr does not go to future release?)

**Comment by CristianZatt** [comment]
I'ts been a long time, I don't think so. You can just use my branch or fork it and make the adjustments you need.

**Comment by tkaczmarzyk** [comment]
Sorry  for the delay guys.... I know it's late, but we will try to check and merge it ASAP.

**Comment by tkaczmarzyk** [comment]
@CristianZatt @youagree Thank you for your contributions. Based on this issue as well as some other issues and pull requests the OffsetDateTime support, as well as other conversions and more comprehensive conversion support, were added to version 2.4.0 (just released)
