### ISSUE TITLE
Usage with @RepositoryRestController

### ISSUE THREAD

**Issue by Arcnor** [tkaczmarzyk/specification-arg-resolver#6]
Is it possible to use this with `@RepositoryRestController`?

I've tried to use it,  but the `SpecificationArgumentResolver` annotation processor is not being called, even after adding it to my `RepositoryRestMvcConfiguration` (instead of the `WebMVCConfigureAdapter`)

**Comment by tkaczmarzyk** [comment]
Thanks for highlighting. I managed to reproduce it. Hmm, it might be tricky, because it seems that `@RepositoryRestController` excludes annotated components from standard Spring MVC handling. I'll look into that and let you know.

**Comment by tkaczmarzyk** [comment]
Ha, just tried something and it worked. Try putting the following into your `RepositoryRestMvcConfiguration`:

```java
 @Override
    protected List<HandlerMethodArgumentResolver> defaultMethodArgumentResolvers() {
        List<HandlerMethodArgumentResolver> resolvers = new ArrayList<>();
        resolvers.addAll(super.defaultMethodArgumentResolvers());
        resolvers.add(new SpecificationArgumentResolver());
        return resolvers;
    }
```

Please let me know if it helped

**Comment by Arcnor** [comment]
Sorry for the delay.

I've tried that, but it didn't seem to work. I'm trying to figure out if it's a problem on my side, but everything works if I use the normal `@RestController` like the `README` specifies...

**Comment by tkaczmarzyk** [comment]
Hmm, you can compare your configuration with the one from my example. It's here: https://github.com/tkaczmarzyk/specification-arg-resolver-example/tree/repo-rest  (branch "repo-rest")
