### ISSUE TITLE
send sepcification object with operator from client

### ISSUE THREAD

**Issue by khodabandelu** [tkaczmarzyk/specification-arg-resolver#64]
Hi guys. I have been searching for something like this library to send object with key and value and operator from the client but I don't find any solution to send the operator from the client to backend in this library. 
Do you have any solution to this problem?

**Comment by azizkhani** [comment]
+1

**Comment by rcbandit111** [comment]
+1

**Comment by tkaczmarzyk** [comment]
Hi, specification-arg-resolver does not support that. Operators are part of the controller configuration. So you send only key/value pair in the request, and the operator is configured (with annotations) on the controller statically.
