### ISSUE TITLE
Joda DateTime

### ISSUE THREAD

**Issue by Aproxim0** [tkaczmarzyk/specification-arg-resolver#66]
SPEC does not work with Joda DateTime, can you fix it, please...

**Comment by Aproxim0** [comment]
Grate!!!!
Does this mean that you will resume work on the project, since the library is very cool, but needs to be improved ...

**Comment by tkaczmarzyk** [comment]
(sorry for the late response -- yes, the project has been resumed (just released 2.2.0 and 2.2.1) -- we will be taking issues from the list, just bit more patience, plese. In the meantime you can response other issues/requests)

**Comment by tkaczmarzyk** [comment]
Hi, please check 2.4.0 release -- it supports java8 datetime types and, if you really need Joda, you can register custom converters (see changelog for 2.40 and the README.md file)
