### ISSUE TITLE
Usage of spring org.springframework.core.convert.ConversionService

### ISSUE THREAD

**Issue by tkleszczynski** [tkaczmarzyk/specification-arg-resolver#72]
Hi. There are several issues already opened regarding conversion from http parameters. #66, #47, #57, #58 
Could library use the same conversion service which is being used by other spring mechanisms? Having this, we could reuse e.g. date formats and other goodies already present in the application.

This would solve converting more cases than just OffsetDateTime or UUID, for which there are opened issues. I would convert the dates to e.g. ZonedDateTime :). Is there any argument against using spring's mechanism?

If no, I'd consider extending it by adding as a fallback somewhere here https://github.com/tkaczmarzyk/specification-arg-resolver/blob/master/src/main/java/net/kaczmarzyk/spring/data/jpa/utils/Converter.java#L116 and then some of the previous common cases could be replaced - having in mind e.g. decimal separators.

What do you think about the idea?

**Comment by jradlica** [comment]
Hi, thank you for the great idea! The fallback mechanism using `ConversionService` will be introduced in v2.4.0 (next release).

**Comment by tkaczmarzyk** [comment]
Thank you very much for your suggestion. This was added in 2.4.0 (just released)!
