### ISSUE TITLE
[Question]: Support for multi level entity joins

### ISSUE THREAD

**Issue by trailapps** [tkaczmarzyk/specification-arg-resolver#73]
Thank you @tkaczmarzyk for open sourcing this library and extensive documentation.
Is there way to join multi level entities, like **Customer->OrderDetail-> Product**
I could find it for single level @https://github.com/tkaczmarzyk/specification-arg-resolver#join

**Comment by ramnasidharta** [comment]
Exact same question where

**Comment by ramnasidharta** [comment]
@trailapps I had to implement my filter by using the default specifications spring-data API. That is, I implemented `Specification` and in `toPredicate()` I used `Root::join` methods to perform the multiple joins. In my case, the query (filter) has a bit complex, so doing this way was good enough.
In case you really want to use the annotations provided by this package, I think there is one solution. But it would work only if you need a two-levels-join: build the query making the middle level entity the root. In other words, if you want to join A with B and then B with C, then do it like this: B right join with A, B left join with C.

**Comment by trailapps** [comment]
Thank you @ramnasidharta for your solution, It works indeed. Instead, I added the join by creating a new specification and it to the specification generated by this library.

**Comment by tkaczmarzyk** [comment]
Multi-level join / join fetch support  has been added in v2.6.0 (just released)
