### ISSUE TITLE
JoinFetch with unnecessary DISTINCT

### ISSUE THREAD

**Issue by Meephistoo** [tkaczmarzyk/specification-arg-resolver#78]
Hi

In some cases when spec-arg-resolved is used with Pageable e.g:
`JpaSpecificationExecutor.findAll(@Nullable Specification<T> spec, Pageable pageable);`

and nested entity property is provided as a sort order postgreSql DB returns error:
"for SELECT DISTINCT, ORDER BY expressions must appear in select list"
So columns from joined tables must appear in SELECT list in case when such columns are used in ORDER BY with DISCTINCT

This  error can be avoided by removing  DISTINCT in SQL 

Is it possible to add to @JoinFetch annotation new property named distinct  with default value = true, and add support in JoinFetch and JoinFetchSpecificationResolver https://github.com/tkaczmarzyk/specification-arg-resolver/blob/master/src/main/java/net/kaczmarzyk/spring/data/jpa/domain/JoinFetch.java#L51
to control DISTINCT usage ?

**Comment by tkaczmarzyk** [comment]
@Meephistoo -- it's included in v2.4.1 (just released)
