### ISSUE TITLE
decoupling SpecificationArgumentResolver from web layer

### ISSUE THREAD

**Issue by ilseva** [tkaczmarzyk/specification-arg-resolver#80]
Hi,
what do you think about decoupling the argument resolver from the web layer?
I think that might be interesting to have the conversion to Specifications at service layer. Is it possible?
Thanks in advance.

**Comment by tkaczmarzyk** [comment]
delivered in https://github.com/tkaczmarzyk/specification-arg-resolver/pull/141, will be released today
