### ISSUE TITLE
Can we filter by property of nested object ?

### ISSUE THREAD

**Issue by durdufatih** [tkaczmarzyk/specification-arg-resolver#86]
Hello I need to filter nested object . I wrote Joins annotation for every entity . But I don't use filter for firstname when I create Specification for Person object .How can I do that? For example

```
class Person{

    @OneToOne
    private Student student;

}

class Student {
     private PersonalInfo personalInfo;
}

class PersonalInfo{

    private String firstName;
    private String lastName;

}
```

Can we use filter for FirstName and LastName property When we create use Specification<Person>

**Comment by jradlica** [comment]
Hi, in the next release (planned for this/next week) should be added support for multi-level joins. Then spec could be like:
```java
@Join(path = "student", alias = "s")
@Join(path = "s.personalInfo", alias = "p")
@And({
      @Spec(path="p.firstName", spec=Equal.class),
      @Spec(path="p.lastName", spec=Equal.class)
})
class FirstNameLastNamePersonSpec extends Specification<Person> {}
``` 

```
  @GetMapping("/persons")
  @ResponseBody
  public Object findPersonsByFirstNameAndLastName(FirstNameLastNamePersonSpec<Person> spec) {
      return repository.findAll(spec);
  }
```

**Comment by tkaczmarzyk** [comment]
Multi-level join / join fetch support  has been added in v2.6.0 (just finished)
