### ISSUE TITLE
Support for custom result objects

### ISSUE THREAD

**Issue by MihajloNesic** [tkaczmarzyk/specification-arg-resolver#96]
The JPA specification allows us to customize results in an object-oriented fashion.

**Suggestion**: `@Result` annotation with `object` attribute

**Example**:

```
GET http://myhost/api/customers?firstName=Homer
```

The handler method:

```java
@RequestMapping(value = "/customers", params = "firstName")
public List<CustomerInfoResponse> findByOrderedItem(
        @Result(object = CustomerInfoResponse.class)
        @Spec(path = "firstName", spec = Like.class)
        Specification<Customer> spec) {

    return customerRepo.findAll(spec);
}
```

And the generated query:

```sql
select new com.example.CustomerInfoResponse(c) from Customer c where c.firstName like '%Homer%'
```

The result object specified **must have** a constructor that matches the projected attributes exactly.

```java
package com.example;

import com.example.entity.Customer;

public class CustomerInfoResponse {

    private Long id;
    private String firstName;
    private String lastName;
    private boolean isBirthdayToday;

    public CustomerInfoResponse(Customer c) {
        this.id = c.getId();
        this.firstName = c.getFirstName();
        this.lastName = c.getLastName();

        // example for other attributes and custom logic
        this.isBirthdayToday = MonthDay.from(LocalDate.now()).equals(MonthDay.from(c.getBirthDate()));
    }

    // getters/setters
}
```

**Comment by tkaczmarzyk** [comment]
Hi @MihajloNesic. this is actually more related to Spring Data JPA than to Specification Argument Resolver. Please see https://github.com/spring-projects/spring-data-jpa/issues/1378 and https://github.com/spring-projects/spring-data-jpa/issues/2274 for more details. It seems that version 3.0 of Spring Data supports it -- and Specification Argument Resolver 3.0 is going to support the latest Spring version. See https://github.com/tkaczmarzyk/specification-arg-resolver/issues/140 for progress tracking:
